#!/bin/bash

# If it's stupid but it works, it isn't stupid.

set -e

if [[ "$1" == "--internal" ]]; then
	internal="true"
	shift
fi

container="$1"
ports="$2"

sourcePort="$(echo -n "$ports" | cut -d':' -f1)"
destinationPort="$(echo -n "$ports" | cut -d':' -f2)"


if [[ "$internal" == "true" ]]; then
	docker run --rm -i --log-driver=none "--net=container:$container" alpine/socat STDIO "TCP4:localhost:$destinationPort"
else
	socat TCP4-LISTEN:$sourcePort,reuseaddr,fork SYSTEM:"$0 --internal $container $destinationPort"
fi



