#!/bin/bash


network="host"
interface="any"


while getopts ":n:i:" opt; do
  case ${opt} in
    n)
      network=$OPTARG
      ;;
    i)
      interface=$OPTARG
      ;;
    \?)
      echo "Invalid option: $OPTARG" 1>&2
      ;;
    :)
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      ;;
  esac
done
shift $((OPTIND -1))

expression="${@:-port not 22}"

id="$(uuidgen)"

/usr/bin/docker run -l id="id=$id" -i --rm "--net=$network" --log-driver=none corfr/tcpdump -i "$interface" -w - "$expression" | wireshark -k -i -

container="$(/usr/bin/docker ps -q --filter "label=id=$id")"

if [[ -n "$container" ]]; then
	/usr/bin/docker stop "$container"
fi
