#!/bin/bash

sshHosts="$(grep -E '^\s*Host(\s+([a-z0-9-]+))+$' ~/.ssh/config | sed -re's,^\s*Host\s+,,' | sed -re 's, ,\n,')"

filteredHosts="$(echo "$sshHosts" | grep -E "$1")"

if [[ -z "$filteredHosts" ]]; then
	echo "Error: Hosts not found" >&2
	exit 1
fi

shift

if [[ -z "$1" ]]; then
	for-all $filteredHosts -- "ssh"
else
	for-all $filteredHosts -- "$*"
fi

