#!/usr/bin/env python

import os
import sys
import subprocess

def main():
    if len(sys.argv) < 2:
        print("Usage: python kitty-run-all.py <command1> <command2> ... <commandN>")
        sys.exit(1)

    commands = sys.argv[1:]

    # Get the current Kitty window ID
    current_window = os.environ.get("KITTY_WINDOW_ID")
    if not current_window:
        print("Error: KITTY_WINDOW_ID environment variable is not set.")
        sys.exit(1)

    # Initialize the list of windows with the current window
    window_ids = [current_window]
    new_window_ids = []

    i = 1
    win = 0

    # Split windows until we have enough for all commands
    while i < len(commands):
        # if command is "|" then skip the next command
        if commands[i] == "|":
            i += 2
            continue

        if len(window_ids) <= win:
            # Starting new round of splittings
            window_ids = new_window_ids
            new_window_ids = []
            win = 0

        # Split each window and add the new windows to the list
        new_window = subprocess.check_output([
            "kitty", "@", "launch", "--type=window", "--cwd", os.getcwd(),
            "--location=hsplit", "--next-to", f"id:{window_ids[win]}",
        ]).strip().decode('utf-8')
        new_window_ids.extend([window_ids[win], new_window])
        i += 1
        win += 1

    # Add the remaining windows to the list
    new_window_ids.extend(window_ids[win:len(window_ids)])
    window_ids = new_window_ids

    i = 1
    win = 1
    while i < len(commands):
        if commands[i] == "|":
            i += 1
            new_window = subprocess.check_output([
                "kitty", "@", "launch", "--type=window", "--cwd", os.getcwd(),
                "--hold", "--location=vsplit", f"--next-to=id:{window_ids[win-1]}", "fish", "-c", f"{commands[i]}\n"])
            window_ids[win-1] = new_window
        else:
            subprocess.run([
                "kitty", "@", "send-text", "--match", f"id:{window_ids[win]}", f"{commands[i]}\n"
            ])
            win += 1

        i += 1

    # focus current_window
    subprocess.run([
        "kitty", "@", "focus-window", f"--match=id:{current_window}"
    ])

    # Run the first command in the current window
    subprocess.run(["fish", "-c", f"{commands[0]}"])

if __name__ == "__main__":
    main()
