#!/bin/bash

namespace="$1"

if [[ -z "$namespace" ]]; then
	kubectl get namespaces
	exit 1
fi

kubectl config set-context --current "--namespace=$namespace"
export DOCKER_MACHINE_NAME="${DOCKER_MACHINE_NAME%%#}#$namespace"

