#!/bin/bash


kubectl get secrets -o json "$@" | jq -r '.items[].data | to_entries | .[] | .key + "#" + .value' | while read line; do
	key="$(echo -n "$line" | cut -f1 -d'#')"
	value="$(echo -n "$line" | cut -f2 -d'#' | base64 -d)"

	echo "$key = '$value'"
done
