#!/bin/bash

scriptDirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $scriptDirectory/common_functions.sh

printHelp() {
	echo ""
	echo "$0"
	echo ""
	echo "Generates random password."
}

if (( $# != 0 )); then
	printHelp
	exit 0
fi

requiresCommand apg

# generate password with only a limited set of symbols, because some sites allow only specific characters
# it is easier to type letters and numbers on Android
apg -n 1 -a 1 -q -m 12 -x 14 -M SNCL -E'{}[]()^&/\\\"'"'" | tr -d '\n'

