#!/bin/bash

scriptDirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $scriptDirectory/common_functions.sh

printHelp() {
	echo ""
	echo "$0"
	echo ""
	echo "Generates random password and stores it in clipboard."
}

requiresCommand xclip

$scriptDirectory/random_password | xclip -selection c

notify-send "Randomly generated password stored in clipboard" > /dev/null 2>&1
