#!/bin/bash

trap "exit 1" ERR

scriptDirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $scriptDirectory/common_functions.sh

printHelp() {
	echo ""
	echo "$0 <interface>"
	echo ""
	echo "Scans network searching for hosts using nmap"
}

if (( $# != 1 )); then
	echo "$0 <interface>"
	echo ""
	echo "For instance: $0 wlan0"
	exit 1
fi

read INET NET _ < <(ip addr show dev "$1" | grep inet)

echo "Scanning for hosts on network: $NET"
nmap -sP "$NET"

