#!/bin/bash

set -e

function cleanup() {
	ssh -S "$controlSocket" -O exit "$host"
	rmdir "$tempDirectory"
}

trap "cleanup" EXIT

tempDirectory="$(mktemp -d)"
controlSocket="$tempDirectory/ssh.control"

sshArgs=()

while true; do
	if [[ "$1" == "-"* ]]; then
		sshArgs+=($1)
	else
		sshArgs+=($1)
		shift
		break;
	fi
	shift
done


ssh -M -S "$controlSocket" -NTf "${sshArgs[@]}"

"$@"



