#!/bin/bash

declare -a params

if [[ "$1" == "-w" ]]; then
	wait="true"
	shift
fi


if [[ "$1" == "-i" ]]; then
	# Run each input line in separate window
	if ifs= read -r line; then
		params+=(new-session "$line" ';')
	fi
	if ifs= read -r line; then
		params+=(split-window -h "$line" ';')
	fi
	while ifs= read -r line; do
		params+=(split-window -v "$line" ';')
	done

else
	# Run each parameter in separate window

	params+=(new-session "$1" ';')
	shift

	if ! [[ -z "$1" ]]; then
		params+=(split-window -v "$1" ';')
		shift
	fi

	if ! [[ -z "$1" ]]; then
		params+=(split-window -fh "$1" ';')
		shift
	fi

	while ! [[ -z "$1" ]]; do
		params+=(split-window -v "$1" ';')
		shift
	done
fi

if [[ "$wait" == "true" ]]; then
	params+=(set remain-on-exit on ';')
fi

tmux "${params[@]}"



