#!/bin/bash

trap "exit 1" ERR

scriptDirectory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $scriptDirectory/common_functions.sh

printHelp() {
	echo ""
	echo "$0"
	echo ""
	echo "Returns Microsoft Windows license key, if it is embedded in BIOS of this machine"
}

if (( $# != 0 )); then
	printHelp
	exit 0
fi

requiresCommand hexdump

sudo hexdump -s 56 -e ' /29 "%s\n"' /sys/firmware/acpi/tables/MSDM
